package mockgenerator

import (
	"bytes"
	"fmt"
	"html/template"
)

const importsTpl = `// Code generated by {{.PkgName}}. DO NOT EDIT.
package main

import (
	connect_go "github.com/bufbuild/connect-go"
	context "context"
	"net/http"
	"golang.org/x/net/http2/h2c"
	"golang.org/x/net/http2"
	"github.com/rs/cors"
	v1 "{{ .GoImportPath }}"
	"{{ .ConnectFilePath }}"
)`

type ImportsStringInput struct {
	PkgName string
	GoImportPath string
	ConnectFilePath string
}

func importsString(i *ImportsStringInput) (string, error) {
	tmpl, err := template.New("imports").Parse(importsTpl)

	if err != nil {
		return "", fmt.Errorf("error parsing template: %w", err)
	}

	buf := bytes.NewBufferString("")

	tmpl.Execute(buf, i)

	return buf.String(), nil
}

// const mainTpl = `func main() {
// 	mux := http.NewServeMux()
// 	server := &GreetServiceMockServer{}
// 	path, handler := greetv1connect.NewGreetServiceHandler(server)
// 	mux.Handle(path, handler)
// 	corsHandler := cors.New(cors.Options{
// 		AllowedOrigins:   []string{"https://buf.build"},
// 		AllowCredentials: true,
// 		AllowedMethods:   []string{http.MethodPost, http.MethodOptions},
// 		AllowedHeaders:   []string{"*"},
// 	}).Handler(mux)
// 	http.ListenAndServe(":8080", h2c.NewHandler(corsHandler, &http2.Server{}))
// }`
